export default {
    SPRINGBOOT_SERVER_HOST: "http://localhost:8080",
    NGINX_SERVER_HOST: "http://localhost:8888",


    TOKEN_NAME_KEY: "_token_name",
    TOKEN_VALUE_KEY: "_token_value",


    ORDER_ALIPAY_SUCCESS: "201",
    BID_ALIPAY_SUCCESS: "202",

    NOT_LOGIN_CODE: 2005,
    THIS_OPERATION_NEEDS_FURTHER_VERIFICATION: 2,
    MODE_RECEPTION: 'reception',
    MODE_BACKSTAGE: 'backstage',
    SSE_MESSAGE_ID_NOTIFY: "0",
    SSE_MESSAGE_ID_USER_MESSAGE: "1",
    SSE_PAYMENT_RESULTS_MESSAGE: "2",

    ORDER_STATUS_REFUNDED: -2,
    ORDER_STATUS_CLOSED: -1,
    ORDER_STATUS_NORMAL: 0,
    ORDER_STATUS_COMPLETED: 1,
}