export default {
    SPRINGBOOT_SERVER_HOST: "http://localhost:8080",
    NGINX_SERVER_HOST: "http://localhost:8888/static/",


    TOKEN_NAME_KEY: "_token_name",
    TOKEN_VALUE_KEY: "_token_value",


    ORDER_ALIPAY_SUCCESS: "201",
    BID_ALIPAY_SUCCESS: "202",

    NOT_LOGIN_CODE: 2005,
    THIS_OPERATION_NEEDS_FURTHER_VERIFICATION: 2,
    MODE_RECEPTION: 'reception',
    MODE_BACKSTAGE: 'backstage',
    SSE_MESSAGE_ID_NOTIFY: "0",
    SSE_MESSAGE_ID_USER_MESSAGE: "1",
    SSE_PAYMENT_RESULTS_MESSAGE: "2",

    ORDER_STATUS_REFUNDED: -3,
    ORDER_STATUS_REFUNDING: -2,
    ORDER_STATUS_CLOSED: -1,
    ORDER_STATUS_NORMAL: 0,
    ORDER_STATUS_COMPLETED: 1,


    CONTENT_TYPE_TEXT: 'TEXT',
    CONTENT_TYPE_IMAGE: 'IMAGE',
    CONTENT_TYPE_VIDEO: 'VIDEO',


    //验证码发送间隔
    SEND_CODE_Interval: 180,


    SCROLLTOP: 325,


    MESSAGE_STATUS_SEND_SUCCESS: 1,
    MESSAGE_STATUS_SENDING: 0,
    MESSAGE_STATUS_SEND_FAILED: -1,

    SEARCH_FOR_COMMODITY: 0,
    SEARCH_FOR_REQUEST: 1,
    TARGET_TYPE_COMMODITY:'商品',
    TARGET_TYPE_REQUEST:'求购',
    TARGET_TYPE_User:'用户',
}